/* Generated By:JJTree&JavaCC: Do not edit this line. MiniSqlConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniSqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_AND = 6;
  /** RegularExpression Id. */
  int K_BY = 7;
  /** RegularExpression Id. */
  int K_CREATE = 8;
  /** RegularExpression Id. */
  int K_DELETE = 9;
  /** RegularExpression Id. */
  int K_DESC = 10;
  /** RegularExpression Id. */
  int K_DESCRIBE = 11;
  /** RegularExpression Id. */
  int K_DISTINCT = 12;
  /** RegularExpression Id. */
  int K_DROP = 13;
  /** RegularExpression Id. */
  int K_EXPLAIN = 14;
  /** RegularExpression Id. */
  int K_HELP = 15;
  /** RegularExpression Id. */
  int K_FLOAT = 16;
  /** RegularExpression Id. */
  int K_FROM = 17;
  /** RegularExpression Id. */
  int K_INDEX = 18;
  /** RegularExpression Id. */
  int K_INSERT = 19;
  /** RegularExpression Id. */
  int K_INTEGER = 20;
  /** RegularExpression Id. */
  int K_INTO = 21;
  /** RegularExpression Id. */
  int K_ON = 22;
  /** RegularExpression Id. */
  int K_OR = 23;
  /** RegularExpression Id. */
  int K_ORDER = 24;
  /** RegularExpression Id. */
  int K_QUIT = 25;
  /** RegularExpression Id. */
  int K_SELECT = 26;
  /** RegularExpression Id. */
  int K_SET = 27;
  /** RegularExpression Id. */
  int K_STRING = 28;
  /** RegularExpression Id. */
  int K_STATS = 29;
  /** RegularExpression Id. */
  int K_TEST = 30;
  /** RegularExpression Id. */
  int K_TABLE = 31;
  /** RegularExpression Id. */
  int K_UPDATE = 32;
  /** RegularExpression Id. */
  int K_VALUES = 33;
  /** RegularExpression Id. */
  int K_WHERE = 34;
  /** RegularExpression Id. */
  int O_EQ = 35;
  /** RegularExpression Id. */
  int O_NEQ = 36;
  /** RegularExpression Id. */
  int O_GT = 37;
  /** RegularExpression Id. */
  int O_GTE = 38;
  /** RegularExpression Id. */
  int O_LT = 39;
  /** RegularExpression Id. */
  int O_LTE = 40;
  /** RegularExpression Id. */
  int O_LPAREN = 41;
  /** RegularExpression Id. */
  int O_RPAREN = 42;
  /** RegularExpression Id. */
  int O_COMMA = 43;
  /** RegularExpression Id. */
  int O_SEMI = 44;
  /** RegularExpression Id. */
  int O_STAR = 45;
  /** RegularExpression Id. */
  int S_INTEGER = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int S_FLOAT = 48;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int SPECIAL_CHAR = 51;
  /** RegularExpression Id. */
  int S_STRING = 52;
  /** RegularExpression Id. */
  int LINE_COMMENT = 53;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AND\"",
    "\"BY\"",
    "\"CREATE\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"EXPLAIN\"",
    "\"HELP\"",
    "\"FLOAT\"",
    "\"FROM\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTO\"",
    "\"ON\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"QUIT\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"STRING\"",
    "\"STATS\"",
    "\"TEST\"",
    "\"TABLE\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"WHERE\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"*\"",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_FLOAT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHAR>",
    "<S_STRING>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
  };

}
